### ISSUE TITLE
Add: Home Page 

### ISSUE THREAD

**Issue by StanzDaniel** [StanzDaniel/Portfolio#1]
### TASKS

- [x] Add Home Page;
- [x] Add Photo Component;
- [x] Add Name Component;
- [x] Add DownArrow Component;
- [x] Add CSS Animations;

### REQUIREMENTS

- [x] Should be Responsive;
- [x] Should be Fast to Load;
- [x] Should have Animations;
- [x] Should navigate to the next section with a single click.
